# build rust nightly each day to notice breakage early
name: daily-nightly
on:
  schedule:
    - cron: "20 17 * * *"
      timezone: "Australia/Perth"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    strategy:
      matrix:
        rust_version: [nightly]
    runs-on: ubuntu-latest
    env:
      RUSTUP_TOOLCHAIN: ${{ matrix.rust_version }}
    steps:
      - uses: actions/checkout@v6

      - name: rust toolchain
        run: rustup component add --toolchain "$RUSTUP_TOOLCHAIN" rustfmt

      - name: Cache Rust files
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
          key: rust-cache1-${{ matrix.rust_version }}-${{ github.run_id }}
          restore-keys: |
            rust-cache1-${{ matrix.rust_version }}

      - name: Format
        run: cargo fmt --check

      - name: Test
        run: |
          cargo test --workspace --exclude sunset-demo-picow --exclude sunset-fuzz
          cargo test -p sunset --all-features
